//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module1Exercise1
{


    public partial class Exercise1
    {

        
        protected global::System.Web.UI.WebControls.Label lblSongInfo;

       
        protected global::System.Web.UI.WebControls.Image imgAlbumCover;

        
        protected global::System.Web.UI.WebControls.Button btnPrev;

       
        protected global::System.Web.UI.WebControls.Button btnPlay;

        
        protected global::System.Web.UI.WebControls.Button btnNext;

        
        protected global::System.Web.UI.WebControls.Label lblNowPlaying;
    }
}
